name: PadawanWallet
options:
  deploymentTarget:
    iOS: '16.1'
targets:
  PadawanWallet:
    type: application
    platform: iOS
    sources:
      - PadawanWallet
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.coyotebitcoin.padawanwallet
      DEVELOPMENT_TEAM: 7Y93MGF3X3
      APP_DISPLAY_NAME: "PadawanWallet"
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      ONLY_ACTIVE_ARCH: YES
    info:
      path: PadawanWallet/Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        ITSAppUsesNonExemptEncryption: NO
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen

  PadawanWalletTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PadawanWalletTests
    dependencies:
      - target: PadawanWallet
    settings:
      INFO_PLIST_FILE: PadawanWalletTests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.coyotebitcoin.padawanwallet.tests

  PadawanWalletUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PadawanWalletUITests
    dependencies:
      - target: PadawanWallet
    settings:
      INFO_PLIST_FILE: PadawanWalletUITests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.coyotebitcoin.padawanwallet.uitests