name: PadawanWallet
options:
  deploymentTarget:
    iOS: '16.1'

packages:
  BitcoinDevKit:
    url: https://github.com/bitcoindevkit/bdk-swift
    version: 2.0.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    version: 4.2.2

targets:
  PadawanWallet:
    type: application
    platform: iOS
    sources:
      - PadawanWallet
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.coyotebitcoin.padawanwallet
      DEVELOPMENT_TEAM: 7Y93MGF3X3
      APP_DISPLAY_NAME: "PadawanWallet"
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      ONLY_ACTIVE_ARCH: YES
    info:
      path: PadawanWallet/Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        ITSAppUsesNonExemptEncryption: NO
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        UIAppFonts:
          - outfit_medium.ttf
          - outfit_regular.ttf
          - outfit_semibold.ttf
          - share_tech_mono.ttf

    dependencies:
      - package: BitcoinDevKit
      - package: KeychainAccess
          
    preBuildScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]
                then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if command -v swiftgen >/dev/null 2>&1
                then
                    echo "Running SwiftGen..."
                    swiftgen
                else
                    echo "error: SwiftGen não está instalado. Use 'brew install swiftgen'."
                    exit 1
                fi
        name: SwiftGen

  PadawanWalletTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PadawanWalletTests
    dependencies:
      - target: PadawanWallet
    settings:
      INFO_PLIST_FILE: PadawanWalletTests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.coyotebitcoin.padawanwallet.tests

  PadawanWalletUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PadawanWalletUITests
    dependencies:
      - target: PadawanWallet
    settings:
      INFO_PLIST_FILE: PadawanWalletUITests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.coyotebitcoin.padawanwallet.uitests