package com.goldenraven.padawanwallet.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF032562) // done
val md_theme_light_onPrimary = Color(0xFFffffff)
// val md_theme_light_primaryContainer = Color(0xFFd0e4ff)
// val md_theme_light_onPrimaryContainer = Color(0xFF001c37)
val md_theme_light_secondary = Color(0xFF3463c7) // done
val md_theme_light_onSecondary = Color(0xFFffffff) // done
// val md_theme_light_secondaryContainer = Color(0xFFffd9e2)
// val md_theme_light_onSecondaryContainer = Color(0xFF3f0019)
val md_theme_light_tertiary = Color(0xFF66e2fc) // done
val md_theme_light_onTertiary = Color(0xFF000000) // done
// val md_theme_light_tertiaryContainer = Color(0xFFb1ecff)
// val md_theme_light_onTertiaryContainer = Color(0xFF001f28)
// val md_theme_light_error = Color(0xFFba1b1b)
// val md_theme_light_errorContainer = Color(0xFFffdad4)
// val md_theme_light_onError = Color(0xFFffffff)
// val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFf8fbfe) // done
val md_theme_light_onBackground = Color(0xFF000000) // done
// val md_theme_light_surface = Color(0xFFfbfdfd)
// val md_theme_light_onSurface = Color(0xFF191c1d)
// val md_theme_light_surfaceVariant = Color(0xFFdfe3ec)
// val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
// val md_theme_light_outline = Color(0xFF73777f)
// val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
// val md_theme_light_inverseSurface = Color(0xFF2d3132)
// val md_theme_light_inversePrimary = Color(0xFF9ecaff)
// val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFb8bb26)
val md_theme_dark_onPrimary = Color(0xFFebdbb2)
val md_theme_dark_primaryContainer = Color(0xFFf50057) // pink
val md_theme_dark_onPrimaryContainer = Color(0xFFf50057) // pink
val md_theme_dark_secondary = Color(0xFFf50057) // pink
val md_theme_dark_onSecondary = Color(0xFFf50057) // pink
val md_theme_dark_secondaryContainer = Color(0xFFf50057) // pink
val md_theme_dark_onSecondaryContainer = Color(0xFFf50057) // pink
val md_theme_dark_tertiary = Color(0xFFf50057) // pink
val md_theme_dark_onTertiary = Color(0xFFf50057) // pink
val md_theme_dark_tertiaryContainer = Color(0xFFf50057) // pink
val md_theme_dark_onTertiaryContainer = Color(0xFFf50057) // pink
val md_theme_dark_error = Color(0xFFcc241d)
val md_theme_dark_errorContainer = Color(0xFFf50057) // pink
val md_theme_dark_onError = Color(0xFFf50057) // pink
val md_theme_dark_onErrorContainer = Color(0xFFf50057) // pink
val md_theme_dark_background = Color(0xFF32302f)
val md_theme_dark_onBackground = Color(0xFFebdbb2)
val md_theme_dark_surface = Color(0xFF504945)
val md_theme_dark_onSurface = Color(0xFFf50057) // pink
val md_theme_dark_surfaceVariant = Color(0xFFf50057) // pink
val md_theme_dark_onSurfaceVariant = Color(0xFFf50057) // pink
val md_theme_dark_outline = Color(0xFFf50057) // pink
val md_theme_dark_inverseOnSurface = Color(0xFFf50057) // pink
val md_theme_dark_inverseSurface = Color(0xFFf50057) // pink
val md_theme_dark_inversePrimary = Color(0xFFf50057) // pink
val md_theme_dark_shadow = Color(0xFFf50057) // pink

val seed = Color(0xFFf50057) // pink
val error = Color(0xFFcc241d)

val md_theme_dark_surfaceLight = Color(0xFF504945)
val md_theme_dark_onBackgroundFaded = Color(0x80ebdbb2)
val md_theme_dark_lightBackground = Color(0xFFf2e5bc)
val md_theme_dark_onLightBackground = Color(0xFF282828)
val md_theme_dark_warning = Color(0xFFfabd2f)


// below are themes I looked into implementing
// the colours were generated using the Material 3 Theme Builder

// new-retro-1
// val md_theme_light_primary = Color(0xFFb12e00)
// val md_theme_light_onPrimary = Color(0xFFffffff)
// val md_theme_light_primaryContainer = Color(0xFFffdacf)
// val md_theme_light_onPrimaryContainer = Color(0xFF3b0900)
// val md_theme_light_secondary = Color(0xFF77574d)
// val md_theme_light_onSecondary = Color(0xFFffffff)
// val md_theme_light_secondaryContainer = Color(0xFFffdacf)
// val md_theme_light_onSecondaryContainer = Color(0xFF2c160f)
// val md_theme_light_tertiary = Color(0xFF6b5d2e)
// val md_theme_light_onTertiary = Color(0xFFffffff)
// val md_theme_light_tertiaryContainer = Color(0xFFf5e1a7)
// val md_theme_light_onTertiaryContainer = Color(0xFF231b00)
// val md_theme_light_error = Color(0xFFba1b1b)
// val md_theme_light_errorContainer = Color(0xFFffdad4)
// val md_theme_light_onError = Color(0xFFffffff)
// val md_theme_light_onErrorContainer = Color(0xFF410001)
// val md_theme_light_background = Color(0xFFfcfcfc)
// val md_theme_light_onBackground = Color(0xFF201a18)
// val md_theme_light_surface = Color(0xFFfcfcfc)
// val md_theme_light_onSurface = Color(0xFF201a18)
// val md_theme_light_surfaceVariant = Color(0xFFf5ded8)
// val md_theme_light_onSurfaceVariant = Color(0xFF53433f)
// val md_theme_light_outline = Color(0xFF85736e)
// val md_theme_light_inverseOnSurface = Color(0xFFfbeeeb)
// val md_theme_light_inverseSurface = Color(0xFF362f2d)
// val md_theme_light_inversePrimary = Color(0xFFffb49d)
// val md_theme_light_shadow = Color(0xFF000000)
//
// val md_theme_dark_primary = Color(0xFFffb49d)
// val md_theme_dark_onPrimary = Color(0xFF601400)
// val md_theme_dark_primaryContainer = Color(0xFF872000)
// val md_theme_dark_onPrimaryContainer = Color(0xFFffdacf)
// val md_theme_dark_secondary = Color(0xFFe7bdb2)
// val md_theme_dark_onSecondary = Color(0xFF442a22)
// val md_theme_dark_secondaryContainer = Color(0xFF5d4037)
// val md_theme_dark_onSecondaryContainer = Color(0xFFffdacf)
// val md_theme_dark_tertiary = Color(0xFFd8c58d)
// val md_theme_dark_onTertiary = Color(0xFF3a2f05)
// val md_theme_dark_tertiaryContainer = Color(0xFF53461a)
// val md_theme_dark_onTertiaryContainer = Color(0xFFf5e1a7)
// val md_theme_dark_error = Color(0xFFffb4a9)
// val md_theme_dark_errorContainer = Color(0xFF930006)
// val md_theme_dark_onError = Color(0xFF680003)
// val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
// val md_theme_dark_background = Color(0xFF201a18)
// val md_theme_dark_onBackground = Color(0xFFede0dd)
// val md_theme_dark_surface = Color(0xFF201a18)
// val md_theme_dark_onSurface = Color(0xFFede0dd)
// val md_theme_dark_surfaceVariant = Color(0xFF53433f)
// val md_theme_dark_onSurfaceVariant = Color(0xFFd8c2bc)
// val md_theme_dark_outline = Color(0xFFa08c87)
// val md_theme_dark_inverseOnSurface = Color(0xFF201a18)
// val md_theme_dark_inverseSurface = Color(0xFFede0dd)
// val md_theme_dark_inversePrimary = Color(0xFFb12e00)
// val md_theme_dark_shadow = Color(0xFF000000)
//
// val seed = Color(0xFFF55826)
// val error = Color(0xFFba1b1b)

// new-retro-2
// val md_theme_light_primary = Color(0xFF7b5900)
// val md_theme_light_onPrimary = Color(0xFFffffff)
// val md_theme_light_primaryContainer = Color(0xFFffde9c)
// val md_theme_light_onPrimaryContainer = Color(0xFF261900)
// val md_theme_light_secondary = Color(0xFF6c5c3f)
// val md_theme_light_onSecondary = Color(0xFFffffff)
// val md_theme_light_secondaryContainer = Color(0xFFf5e0bb)
// val md_theme_light_onSecondaryContainer = Color(0xFF241a04)
// val md_theme_light_tertiary = Color(0xFF4a6545)
// val md_theme_light_onTertiary = Color(0xFFffffff)
// val md_theme_light_tertiaryContainer = Color(0xFFccebc3)
// val md_theme_light_onTertiaryContainer = Color(0xFF082008)
// val md_theme_light_error = Color(0xFFba1b1b)
// val md_theme_light_errorContainer = Color(0xFFffdad4)
// val md_theme_light_onError = Color(0xFFffffff)
// val md_theme_light_onErrorContainer = Color(0xFF410001)
// val md_theme_light_background = Color(0xFFfffbf8)
// val md_theme_light_onBackground = Color(0xFF1e1b16)
// val md_theme_light_surface = Color(0xFFfffbf8)
// val md_theme_light_onSurface = Color(0xFF1e1b16)
// val md_theme_light_surfaceVariant = Color(0xFFede1cf)
// val md_theme_light_onSurfaceVariant = Color(0xFF4e4639)
// val md_theme_light_outline = Color(0xFF7f7667)
// val md_theme_light_inverseOnSurface = Color(0xFFf7efe6)
// val md_theme_light_inverseSurface = Color(0xFF34302a)
// val md_theme_light_inversePrimary = Color(0xFFf8bd2d)
// val md_theme_light_shadow = Color(0xFF000000)
//
// val md_theme_dark_primary = Color(0xFFf8bd2d)
// val md_theme_dark_onPrimary = Color(0xFF412d00)
// val md_theme_dark_primaryContainer = Color(0xFF5c4200)
// val md_theme_dark_onPrimaryContainer = Color(0xFFffde9c)
// val md_theme_dark_secondary = Color(0xFFd8c4a0)
// val md_theme_dark_onSecondary = Color(0xFF3b2f16)
// val md_theme_dark_secondaryContainer = Color(0xFF534529)
// val md_theme_dark_onSecondaryContainer = Color(0xFFf5e0bb)
// val md_theme_dark_tertiary = Color(0xFFb1cfa8)
// val md_theme_dark_onTertiary = Color(0xFF1e361b)
// val md_theme_dark_tertiaryContainer = Color(0xFF344d30)
// val md_theme_dark_onTertiaryContainer = Color(0xFFccebc3)
// val md_theme_dark_error = Color(0xFFffb4a9)
// val md_theme_dark_errorContainer = Color(0xFF930006)
// val md_theme_dark_onError = Color(0xFF680003)
// val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
// val md_theme_dark_background = Color(0xFF1e1b16)
// val md_theme_dark_onBackground = Color(0xFFe9e1d8)
// val md_theme_dark_surface = Color(0xFF1e1b16)
// val md_theme_dark_onSurface = Color(0xFFe9e1d8)
// val md_theme_dark_surfaceVariant = Color(0xFF4e4639)
// val md_theme_dark_onSurfaceVariant = Color(0xFFd1c5b4)
// val md_theme_dark_outline = Color(0xFF998f7f)
// val md_theme_dark_inverseOnSurface = Color(0xFF1e1b16)
// val md_theme_dark_inverseSurface = Color(0xFFe9e1d8)
// val md_theme_dark_inversePrimary = Color(0xFF7b5900)
// val md_theme_dark_shadow = Color(0xFF000000)
//
// val seed = Color(0xFFF6BB2B)
// val error = Color(0xFFba1b1b)

// new-retro-3
// val md_theme_light_primary = Color(0xFF526600)
// val md_theme_light_onPrimary = Color(0xFFffffff)
// val md_theme_light_primaryContainer = Color(0xFFd4ee7f)
// val md_theme_light_onPrimaryContainer = Color(0xFF161f00)
// val md_theme_light_secondary = Color(0xFF5b6146)
// val md_theme_light_onSecondary = Color(0xFFffffff)
// val md_theme_light_secondaryContainer = Color(0xFFe0e6c3)
// val md_theme_light_onSecondaryContainer = Color(0xFF191d08)
// val md_theme_light_tertiary = Color(0xFF3a665e)
// val md_theme_light_onTertiary = Color(0xFFffffff)
// val md_theme_light_tertiaryContainer = Color(0xFFbdece1)
// val md_theme_light_onTertiaryContainer = Color(0xFF00201b)
// val md_theme_light_error = Color(0xFFba1b1b)
// val md_theme_light_errorContainer = Color(0xFFffdad4)
// val md_theme_light_onError = Color(0xFFffffff)
// val md_theme_light_onErrorContainer = Color(0xFF410001)
// val md_theme_light_background = Color(0xFFfefcf4)
// val md_theme_light_onBackground = Color(0xFF1b1c17)
// val md_theme_light_surface = Color(0xFFfefcf4)
// val md_theme_light_onSurface = Color(0xFF1b1c17)
// val md_theme_light_surfaceVariant = Color(0xFFe3e4d3)
// val md_theme_light_onSurfaceVariant = Color(0xFF46483c)
// val md_theme_light_outline = Color(0xFF77786b)
// val md_theme_light_inverseOnSurface = Color(0xFFf3f1e9)
// val md_theme_light_inverseSurface = Color(0xFF30312b)
// val md_theme_light_inversePrimary = Color(0xFFb8d166)
// val md_theme_light_shadow = Color(0xFF000000)
//
// val md_theme_dark_primary = Color(0xFFb8d166)
// val md_theme_dark_onPrimary = Color(0xFF283500)
// val md_theme_dark_primaryContainer = Color(0xFF3c4d00)
// val md_theme_dark_onPrimaryContainer = Color(0xFFd4ee7f)
// val md_theme_dark_secondary = Color(0xFFc4caa9)
// val md_theme_dark_onSecondary = Color(0xFF2e331c)
// val md_theme_dark_secondaryContainer = Color(0xFF444930)
// val md_theme_dark_onSecondaryContainer = Color(0xFFe0e6c3)
// val md_theme_dark_tertiary = Color(0xFFa1d0c5)
// val md_theme_dark_onTertiary = Color(0xFF033730)
// val md_theme_dark_tertiaryContainer = Color(0xFF214e46)
// val md_theme_dark_onTertiaryContainer = Color(0xFFbdece1)
// val md_theme_dark_error = Color(0xFFffb4a9)
// val md_theme_dark_errorContainer = Color(0xFF930006)
// val md_theme_dark_onError = Color(0xFF680003)
// val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
// val md_theme_dark_background = Color(0xFF1b1c17)
// val md_theme_dark_onBackground = Color(0xFFe5e3db)
// val md_theme_dark_surface = Color(0xFF1b1c17)
// val md_theme_dark_onSurface = Color(0xFFe5e3db)
// val md_theme_dark_surfaceVariant = Color(0xFF46483c)
// val md_theme_dark_onSurfaceVariant = Color(0xFFc7c8b8)
// val md_theme_dark_outline = Color(0xFF909283)
// val md_theme_dark_inverseOnSurface = Color(0xFF1b1c17)
// val md_theme_dark_inverseSurface = Color(0xFFe5e3db)
// val md_theme_dark_inversePrimary = Color(0xFF526600)
// val md_theme_dark_shadow = Color(0xFF000000)
//
// val seed = Color(0xFF7A884C)
// val error = Color(0xFFba1b1b)

// custom-m3-padawan
// #006bb6 (blue)
// #2f292a (dark blue)
// #9bdff6 (light blue)
// #fffefc (background)
// val md_theme_light_primary = Color(0xFF006bb6) // customized
// val md_theme_light_onPrimary = Color(0xFFffffff)
// val md_theme_light_primaryContainer = Color(0xFFd0e4ff)
// val md_theme_light_onPrimaryContainer = Color(0xFF001c37)
// val md_theme_light_secondary = Color(0xFF2f292a) // customized
// val md_theme_light_onSecondary = Color(0xFFffffff)
// val md_theme_light_secondaryContainer = Color(0xFFffd9e2)
// val md_theme_light_onSecondaryContainer = Color(0xFF3f0019)
// val md_theme_light_tertiary = Color(0xFF9bdff6) // customized
// val md_theme_light_onTertiary = Color(0xFFffffff)
// val md_theme_light_tertiaryContainer = Color(0xFFb1ecff)
// val md_theme_light_onTertiaryContainer = Color(0xFF001f28)
// val md_theme_light_error = Color(0xFFba1b1b)
// val md_theme_light_errorContainer = Color(0xFFffdad4)
// val md_theme_light_onError = Color(0xFFffffff)
// val md_theme_light_onErrorContainer = Color(0xFF410001)
// val md_theme_light_background = Color(0xFFfffefc) // customized
// val md_theme_light_onBackground = Color(0xFF191c1d)
// val md_theme_light_surface = Color(0xFFfbfdfd)
// val md_theme_light_onSurface = Color(0xFF191c1d)
// val md_theme_light_surfaceVariant = Color(0xFFdfe3ec)
// val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
// val md_theme_light_outline = Color(0xFF73777f)
// val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
// val md_theme_light_inverseSurface = Color(0xFF2d3132)
// val md_theme_light_inversePrimary = Color(0xFF9ecaff)
// val md_theme_light_shadow = Color(0xFF000000)
//
// val md_theme_dark_primary = Color(0xFF9ecaff)
// val md_theme_dark_onPrimary = Color(0xFF00325b)
// val md_theme_dark_primaryContainer = Color(0xFF00487f)
// val md_theme_dark_onPrimaryContainer = Color(0xFFd0e4ff)
// val md_theme_dark_secondary = Color(0xFFffb1c6)
// val md_theme_dark_onSecondary = Color(0xFF5e102e)
// val md_theme_dark_secondaryContainer = Color(0xFF7c2945)
// val md_theme_dark_onSecondaryContainer = Color(0xFFffd9e2)
// val md_theme_dark_tertiary = Color(0xFF59d5f8)
// val md_theme_dark_onTertiary = Color(0xFF003542)
// val md_theme_dark_tertiaryContainer = Color(0xFF004e60)
// val md_theme_dark_onTertiaryContainer = Color(0xFFb1ecff)
// val md_theme_dark_error = Color(0xFFffb4a9)
// val md_theme_dark_errorContainer = Color(0xFF930006)
// val md_theme_dark_onError = Color(0xFF680003)
// val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
// val md_theme_dark_background = Color(0xFF191c1d)
// val md_theme_dark_onBackground = Color(0xFFe0e3e3)
// val md_theme_dark_surface = Color(0xFF191c1d)
// val md_theme_dark_onSurface = Color(0xFFe0e3e3)
// val md_theme_dark_surfaceVariant = Color(0xFF43474e)
// val md_theme_dark_onSurfaceVariant = Color(0xFFc3c7d0)
// val md_theme_dark_outline = Color(0xFF8d9199)
// val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
// val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)
// val md_theme_dark_inversePrimary = Color(0xFF0060a7)
// val md_theme_dark_shadow = Color(0xFF000000)
//
// val seed = Color(0xFF006bb6)
// val error = Color(0xFFba1b1b)
