name: Android Build

on: pull_request

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests
        run: ./gradlew test

  instrumentation_tests:
    name: Instrumentation Tests
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [26, 31]
        arch: [x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck 