name: Run Android Unit Tests

on:
  push:
    paths:
      - "Android/**"
  pull_request:
    paths:
      - "Android/**"
  workflow_dispatch:

jobs: 
  unit_tests:
    name: "Run unit tests"
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./Android/
    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: "Run unit tests"
        run: ./gradlew test --no-daemon --stacktrace
